trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  displayName: Setup authentication
  inputs:
    azureSubscription: 'demo-SP'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      # Set this header to allow terragrunt to clone other git repositories
        echo "starting pipeline"
        git config --global http.extraheader "AUTHORIZATION: bearer $(System.AccessToken)"
        echo "after 1"
        subscriptionId=$(az account show --query id -o tsv)
        echo $subscriptionId
        echo "##vso[task.setvariable variable=ARM_CLIENT_ID;]$servicePrincipalId"
        echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;]$servicePrincipalKey"
        echo "##vso[task.setvariable variable=ARM_TENANT_ID;]$tenantId"
        echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID;]$subscriptionId"
    
        echo $ARM_CLIENT_ID
        echo ARM_CLIENT_ID
    addSpnToEnvironment: true

- task: AzureCLI@2
  displayName: login manual
  inputs:
    azureSubscription: 'demo-SP'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: | 
        echo "next"
        az login --service-principal --username $ARM_CLIENT_ID --password $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
        echo "next12"
        az account show
        echo $ARM_CLIENT_ID
        echo $ARM_CLIENT_SECRET
        echo $ARM_TENANT_ID


 